Repository feldera/feldera, pull requests merged in 2025-01, with the labels that each got.

#3252 dbsp_adapters: Add comments.
  crates/adapters/src/server/mod.rs
Labels: adapters, rust

#3234 [WebConsole] Fix Change Stream and Ad-Hoc Query tables flicker in Safari
  web-console/src/lib/components/adhoc/Query.svelte
  web-console/src/lib/components/common/virtualList/HeadlessVirtualList.svelte
  web-console/src/lib/components/pipelines/editor/ChangeStream.svelte
  web-console/src/lib/components/pipelines/editor/ReverseScrollFixedList.svelte
Labels: bug, Web Console, javascript

#3269 [docs] Improve SQL doc structure.
  docs/sidebars.js
  docs/sql/ad-hoc.md
  docs/sql/aggregates.md
  docs/sql/binary.md
  docs/sql/casts.md
  docs/sql/datetime.md
  docs/sql/decimal.md
  docs/sql/float.md
  docs/sql/function-index.md
  docs/sql/index.mdx
  docs/sql/json.md
  docs/sql/recursion.mdx
  docs/sql/string.md
  docs/sql/system.md
  docs/sql/table.md
  docs/sql/types.md
  docs/sql/udf.md
Labels: documentation

#3271 [docs] Use case: policy engine.
  demo/packaged/sql/07-fine-grained-authorization.sql
  demo/packaged/sql/08-dynamic-fga.sql
  demo/packaged/sql/08-dynamic-fga.udf.rs
  demo/packaged/sql/08-dynamic-fga.udf.toml
  docs/sidebars.js
  docs/use_cases/fine_grained_authorization/dynamic.md
  docs/use_cases/fine_grained_authorization/fga-architecture-incremental.png
  docs/use_cases/fine_grained_authorization/fga-architecture.png
  docs/use_cases/fine_grained_authorization/intro.md
  docs/use_cases/fine_grained_authorization/object-graph.png
  docs/use_cases/fine_grained_authorization/static.md
Labels: documentation

#3284 [adapters] Fix program schema parser.
  crates/feldera-types/src/program_schema.rs
Labels: adapters

#3296 dbsp: Disable missing documentation warnings for test-only items.
  crates/dbsp/src/storage/file/mod.rs
Labels: rust

#3273 [SQL] Better error messages involving string and decimal types (#3247)
  sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/primitive/DBSPTypeDecimal.java
  sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/primitive/DBSPTypeString.java
  sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/RegressionTests.java
  sql-to-dbsp-compiler/build.sh
Labels: Calcite

#3300 [dbsp] schedule circuits using tokio.
  Cargo.lock
  crates/dbsp/Cargo.toml
  crates/dbsp/src/circuit/circuit_builder.rs
  crates/dbsp/src/circuit/operator_traits.rs
  crates/dbsp/src/circuit/runtime.rs
  crates/dbsp/src/circuit/schedule/dynamic_scheduler.rs
  crates/dbsp/src/circuit/schedule/mod.rs
  crates/dbsp/src/circuit/schedule/static_scheduler.rs
  crates/dbsp/src/operator/apply.rs
  crates/dbsp/src/operator/apply2.rs
  crates/dbsp/src/operator/apply3.rs
  crates/dbsp/src/operator/apply_n.rs
  crates/dbsp/src/operator/communication/exchange.rs
  crates/dbsp/src/operator/condition.rs
  crates/dbsp/src/operator/csv.rs
  crates/dbsp/src/operator/delta0.rs
  crates/dbsp/src/operator/dynamic/aggregate/chain_aggregate.rs
  crates/dbsp/src/operator/dynamic/aggregate/mod.rs
  crates/dbsp/src/operator/dynamic/asof_join.rs
  crates/dbsp/src/operator/dynamic/communication/gather.rs
  crates/dbsp/src/operator/dynamic/consolidate.rs
  crates/dbsp/src/operator/dynamic/controlled_filter.rs
  crates/dbsp/src/operator/dynamic/distinct.rs
  crates/dbsp/src/operator/dynamic/filter_map.rs
  crates/dbsp/src/operator/dynamic/group/mod.rs
  crates/dbsp/src/operator/dynamic/index.rs
  crates/dbsp/src/operator/dynamic/input_upsert.rs
  crates/dbsp/src/operator/dynamic/join.rs
  crates/dbsp/src/operator/dynamic/join_range.rs
  crates/dbsp/src/operator/dynamic/neighborhood.rs
  crates/dbsp/src/operator/dynamic/sample.rs
  crates/dbsp/src/operator/dynamic/semijoin.rs
  crates/dbsp/src/operator/dynamic/time_series/radix_tree/partitioned_tree_aggregate.rs
  crates/dbsp/src/operator/dynamic/time_series/radix_tree/tree_aggregate.rs
  crates/dbsp/src/operator/dynamic/time_series/rolling_aggregate.rs
  crates/dbsp/src/operator/dynamic/time_series/window.rs
  crates/dbsp/src/operator/dynamic/trace.rs
  crates/dbsp/src/operator/dynamic/upsert.rs
  crates/dbsp/src/operator/generator.rs
  crates/dbsp/src/operator/input.rs
  crates/dbsp/src/operator/inspect.rs
  crates/dbsp/src/operator/neg.rs
  crates/dbsp/src/operator/output.rs
  crates/dbsp/src/operator/plus.rs
  crates/dbsp/src/operator/sum.rs
  crates/dbsp/src/operator/z1.rs
Labels: DBSP core, storage

#3321 [docs] Index page for the Guides section.
  docs/sidebars.js
  docs/tutorials/index.md
Labels: documentation

#3320 Broken doc references inREADME.md
  README.md
Labels: documentation

#3346 [docs] Typo in delta connector docs
  docs/connectors/sinks/delta.md
Labels: documentation

#3347 [docs] Typo in FGA use case.
  docs/use_cases/fine_grained_authorization/intro.md
Labels: documentation

#3377 [adapters] s3: Avoid panic when adapter exits before reading all the …
  crates/adapters/src/transport/s3/mod.rs
Labels: bug, adapters, user-reported

#3385 [adapters] Reduce serde code.
  crates/adapters/src/format/avro/deserializer.rs
  crates/adapters/src/static_compile/deinput.rs
Labels: adapters

#3389 [dbsp] Disable io_uring storage by default.
  crates/dbsp/src/storage/backend/mod.rs
Labels: performance, storage, rust

#3394 [dbsp] The sum of sharded streams is sharded.
  crates/dbsp/src/operator/sum.rs
Labels: DBSP core
