Repository feldera/feldera, pull requests merged in 2025-10, with the labels that each got.

#4845 Make Delta connectors robust to S3 timeouts.
  Cargo.lock
  Cargo.toml
  crates/adapters/Cargo.toml
  crates/adapters/src/integrated/delta_table/input.rs
  crates/adapters/src/integrated/delta_table/output.rs
Labels: connectors

#4839 [WebConsole] Fix cursor jumps to beginning when pipeline polling is in flight
  web-console/src/lib/components/layout/pipelines/PipelineConfigurationsPopup.svelte
  web-console/src/lib/components/layout/pipelines/PipelineEditLayout.svelte
  web-console/src/lib/components/layout/pipelines/PipelineToolbarMenuPopup.svelte
  web-console/src/lib/components/pipelines/list/Actions.svelte
  web-console/src/lib/compositions/usePipelineAction.svelte.ts
  web-console/src/lib/compositions/useWritablePipeline.svelte.ts
  web-console/src/lib/services/pipelineManager.ts
  web-console/src/routes/(system)/(authenticated)/(pipelines)/pipelines/[pipelineName]/+page.svelte
Labels: javascript, UX

#4851 [adapters] Fix initialization race.
  crates/adapters/src/controller.rs
Labels: bug, connectors, rust
